%% create spaces for pupil tracking + running speed 

timestamps_interval = 1/framerate
sample_data = zeros(1, 1000);
pupil_tracking_data = types.core.TimeSeries(...
    'starting_time_unit', 'seconds',...
    'timestamps_interval', timestamps_interval,...
    'timestamps_unit', 'seconds',...
    'data', sample_data,...
    'description', 'this is the pupil tracking data',...
    'data_unit', 'seconds')

nwb.acquisition.set('pupil_tracking', pupil_tracking_data)

running_speed_data = types.core.TimeSeries(...
    'starting_time_unit', 'seconds',...
    'timestamps_interval', timestamps_interval,...
    'timestamps_unit', 'seconds',...
    'data', sample_data,...
    'description', 'this is the running speed data',...
    'data_unit', 'mph')

nwb.acquisition.set('running_speed', running_speed_data)
